name: CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20-alpine 
    steps:
      - name: Install git and rsync 📚
        run: |
          apk update && apk add git rsync

      - uses: actions/checkout@v4

      - name: Install dependencies 
        run: npm install

      - name: Build Antora project 
        run: |
            set -e
            echo "Creando carpeta supplemental-ui..."
            mkdir -p supplemental-ui
            echo "Copiando archivos..."
            cp -R node_modules/@antora/lunr-extension/supplemental_ui/* supplemental-ui/ || true

            echo "Ejecutando Antora..."
            npx antora local-antora-playbook.yml --fetch

      - name: Verificar build
        run: |
            echo "Mostrando estructura de archivos:"
            ls -R

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: contains(github.ref, 'refs/heads/main') 
        with:
          branch: gh-pages 
          folder: build/site
          clean: true