name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # 👈 esto es lo que faltaba

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20-alpine
    steps:
      - name: Install git and rsync
        run: apk update && apk add git rsync

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build Antora project
        run: |
          cp -R node_modules/@antora/lunr-extension/supplemental_ui/* supplemental-ui/
          npx antora local-antora-playbook.yml --fetch

      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: contains(github.ref, 'refs/heads/main')
        with:  
          branch: gh-pages
          folder: docs
          clean: true